### PR TITLE
[#175]: Run analysis on external contributions

### PR DESCRIPTION
**Pull request by GwnDaan**
### What's new
- SonarCloud should now be able to run on external PR's when an admin has approved the PR's content.
- Merged all similar CI workflows into one single workflow with multiple jobs.

**Note (@ad3154):**  for this to work well, a dummy environment has to be created in the project settings called "Integrate Pull Request" according to [source](https://dev.to/petrsvihlik/using-environment-protection-rules-to-secure-secrets-when-building-external-forks-with-pullrequesttarget-hci).

### CODE REVIEW

**Comment by ad3154** [comment]
I've created that environment now according to those instructions

**Comment by GwnDaan** [comment]
> I've created that environment now according to those instructions

Sounds good! It's kind of frustratig that the build workflow will only run on the next PR after this PR is merged, at least that is how I understand it. 

Or is there some other way to force the workflow to run? That would be useful to refine it and make sure it works without having to merge...

I think I can try to do some testing with it in my forked repo.

**Comment by ad3154** [comment]
I'm not sure if there's a way to force run it... I'll go ahead and merge it in and we can see how it goes.

**Comment by GwnDaan** [comment]
I'll make a PR for a fix, and then we can see whether it works for a PR or not

**Pull request merged**
